//Function which generates a random number from (0-8)
//Takes no arguments
//Returns:
//	1) r0: the randomly generated number
.global	randomNumber
randomNumber:
	push	{lr}

	mov	r0, #0			//		
	bl	time			//
	
	mov	r1, r0			//
	bl	srand			//

	bl	rand			//
	mov	r4, r0			//generate a random number and store it in r4

	mov	r5, #0x7		//Bitmask
	
	and	r0, r5, r4		//use bitmask to get last 3 bit of random number

	pop	{lr}
	mov	pc, lr

//Function which sets the position of the value packs to one of 9 possible locations
//Location is determined by a random number generated above
//Takes 1 argument:
//	1) r0: a number from 0-8
//Returns nothing
.global setValuePackPositions
setValuePackPositions:
	push	{r4-r11, lr}

position0:
	cmp	r0, #0			//if r0 is 0
	bne	position1		//set the value packs in position 1
					//else, check if r0 is 1, then 2 and so on

	mov	r1, #144		//set x position of paddle value pack 1
	mov	r2, #384		//set y position of paddle value pack 1
	
	mov	r3, #784		//set x position of paddle value pack 2
	mov	r4, #288		//set y position of paddle value pack 2

	mov	r5, #464		//set x position of catch ball value pack 1
	mov	r6, #224		//set y position of catch ball value pack 2
	
	mov	r8, #1168		//set X position of catch ball value pack 2
	mov	r9, #384		//set y position of catch ball value pack 2

	mov	r10, #336		// set x position of brick value pack
	mov	r11, #128		// set y position of brick value pack

	b	SVPPReturn

position1:				
					//the above procedure is repeated above 7 times for different positions
					//position is selected based on argument in r0
					//argument passed into r0 is a randomly generated number from (0-8)
					//this number is randomly generated by the randomNumber function above
	cmp	r0, #1
	bne	position2

	mov	r1, #656
	mov	r2, #192
	
	mov	r3, #656
	mov	r4, #480

	mov	r5, #208
	mov	r6, #416
	
	mov	r8, #912
	mov	r9, #224

	mov	r10, #336		
	mov	r11, #128

	b	SVPPReturn
position2:
	cmp	r0, #2
	bne	position3

	mov	r1, #208
	mov	r2, #448
	
	mov	r3, #1040
	mov	r4, #224

	mov	r5, #656
	mov	r6, #480
	
	mov	r8, #464
	mov	r9, #288

	mov	r10, #976		
	mov	r11, #480

	b	SVPPReturn
position3:
	cmp	r0, #3
	bne	position4

	mov	r1, #1040
	mov	r2, #192
	
	mov	r3, #208
	mov	r4, #352

	mov	r5, #784
	mov	r6, #480
	
	mov	r8, #720
	mov	r9, #224

	mov	r10, #464		
	mov	r11, #352

	b	SVPPReturn
position4:
	cmp	r0, #4
	bne	position5

	mov	r1, #592
	mov	r2, #448
	
	mov	r3, #784
	mov	r4, #320

	mov	r5, #656
	mov	r6, #448
	
	mov	r8, #272
	mov	r9, #288

	mov	r10, #720		
	mov	r11, #448

	b	SVPPReturn
position5:
	cmp	r0, #5
	bne	position6

	mov	r1, #336
	mov	r2, #192
	
	mov	r3, #976
	mov	r4, #192

	mov	r5, #912
	mov	r6, #416
	
	mov	r8, #464
	mov	r9, #544

	mov	r10, #144		
	mov	r11, #352

	b	SVPPReturn
position6:
	cmp	r0, #6
	bne	position7

	mov	r1, #1040
	mov	r2, #448
	
	mov	r3, #656
	mov	r4, #480

	mov	r5, #464
	mov	r6, #288
	
	mov	r8, #272
	mov	r9, #512

	mov	r10, #592		
	mov	r11, #288


	b	SVPPReturn
position7:
	
	mov	r1, #720
	mov	r2, #480
	
	mov	r3, #912
	mov	r4, #384

	mov	r5, #912
	mov	r6, #352
	
	mov	r8, #400
	mov	r9, #224
	
	mov	r10, #848		
	mov	r11, #192

SVPPReturn:

	mov	r0, #0

	ldr	r7, =valuePaddleState2
	str	r1, [r7]		//paddle value pack 1 x position
	str	r2, [r7, #4]		//paddle value pack 1 y position
	str	r2, [r7, #8]		//paddle value pack 1 y initial position
	str	r0, [r7, #12]		//paddle value pack 1 enabled flag
	

	ldr	r7, =valuePaddleState		
	str	r3, [r7]		//paddle value pack 2 x position
	str	r4, [r7, #4]		//paddle value pack 2 y position
	str	r4, [r7, #8]		//paddle value pack 2 y initial position
	str	r0, [r7, #12]		//paddle value pack 2 enabled flag

	ldr	r7, =valueBallState2		
	str	r5, [r7]		//catch ball value pack 1 x position
	str	r6, [r7, #4]		//catch ball value pack 1 y position
	str	r6, [r7, #8]		//catch ball value pack 1 y initial position
	str	r0, [r7, #12]		//catch ball value pack 1 enabled flag
	

	ldr	r7, =valueBallState		
	str	r8, [r7]		//catch ball value pack 2 x position
	str	r9, [r7, #4]		//catch ball value pack 2 y position
	str	r9, [r7, #8]		//catch ball value pack 2 y initial position
	str	r0, [r7, #12]		//catch ball value pack 2 enabled flag

	ldr	r7, =valueBrickState	
	str	r10, [r7]		//catch ball value pack 2 x position
	str	r11, [r7, #4]		//catch ball value pack 2 y position
	str	r11, [r7, #8]		//catch ball value pack 2 y initial position
	str	r0, [r7, #12]		//catch ball value pack 2 enabled flag
	
	pop	{r4-r11, lr}
	mov	pc, lr
